### ISSUE TITLE
RunTImeRrror：max_pool2d_with_indices_out_cuda_frame failed with error code 0

### ISSUE THREAD

**Issue by GuHuangAI** [princeton-vl/pytorch_stacked_hourglass#6]
when i run `python train.py -e test_run_001`  the error occured:
`loading data...
Done (t=4.74s)
epoch:  0
start train test_run_001
  0% 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 127, in <module>
    main()
  File "train.py", line 123, in main
    train(func, data_func, config)
  File "train.py", line 94, in train
    outs = train_func(batch_id + i, config, phase, **datas)
  File "/content/pytorch_stacked_hourglass/task/pose.py", line 110, in make_train
    result = net(inputs['imgs'], **{i:inputs[i] for i in inputs if i!='imgs'})
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/pytorch_stacked_hourglass/task/pose.py", line 68, in forward
    combined_hm_preds = self.model(imgs, **inps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/pytorch_stacked_hourglass/models/posenet.py", line 54, in forward
    hg = self.hgs[i](x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/pytorch_stacked_hourglass/models/layers.py", line 81, in forward
    pool1 = self.pool1(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/pooling.py", line 141, in forward
    self.return_indices)
  File "/usr/local/lib/python3.6/dist-packages/torch/_jit_internal.py", line 181, in fn
    return if_false(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 488, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: max_pool2d_with_indices_out_cuda_frame failed with error code 0`
could you give me some help?

**Comment by GuHuangAI** [comment]
i've solved it. the reason is that the version of my pytorch is 1.3.0. just uninstall is and install 1.0.0.
